Scrapper, Damir Khamidullin - 22FPL2
fipl-hse/2023-2-level-ctlr pull request #15
Opened 2024-04-01 10:35 UTC by Damir-Khamidullin

2024-04-12 15:32 UTC, demid5111 commented
nothing to review

2024-04-19 09:21 UTC, demid5111 commented
nothing to review, conflicts

2024-04-24 19:42 UTC, demid5111 requested changes
seems that you only started. good luck!

2024-04-24 19:42 UTC, demid5111 commented on requirements.txt
> +requests==2.31.0
.

2024-04-24 19:42 UTC, demid5111 commented on lab_5_scrapper/target_score.txt
you have to add admins (me, Dmitry Yurievich and Vasilisa) to collaborators. otherwise you PR will not be accepted.

2024-04-24 19:42 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +    return requests.get(url, headers=config.get_headers(), timeout=config.get_timeout())
where are sleeps among neighbor reqiests?

2024-04-24 19:42 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +    pass
provide docstring to each exception class

2024-04-26 11:32 UTC, demid5111 commented
nothing to review

2024-05-02 06:35 UTC, demid5111 commented
nothing to review

2024-05-02 11:52 UTC, dmitry-uraev commented
No progress since last review

2024-05-22 17:26 UTC, dmitry-uraev commented
No progress since last review

2024-05-26 16:35 UTC, dmitry-uraev commented
i suggest you should increase your mark as you have 4 and missed deadline -2

that is you may need at least 6 to get 4

2024-05-28 20:02 UTC, closed without merging